spring.application.name=FilmRentalFrontend
server.port=8081
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

backend.api.url.films=http://localhost:8080/api/films
backend.api.url.actors=http://localhost:8080/api/actors
backend.api.url.customers=http://localhost:8080/api/customers
backend.api.url.payment=http://localhost:8080/api/payment
backend.api.url.cities=http://localhost:8080/api/cities
backend.api.url.inventory=http://localhost:8080/api/inventory
backend.api.url.rental=http://localhost:8080/api/rental
backend.api.url.staff=http://localhost:8080/api/staff

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

logging.level.com.filmrentalfrontend=DEBUG
logging.level.org.thymeleaf=DEBUG